import { UserProvider } from "@/service/user/UserProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { headers } from "next/headers";
import WalletProvider from "../service/wagmi/provider/walletProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookies = (await headers()).get('cookie')

  return (
    <html lang="en">
      <body>
        <WalletProvider cookies={cookies}>
          <UserProvider>
            {children}
          </UserProvider>
        </WalletProvider>
      </body>
    </html>
  )
}